
name: Duplicate Branch For Test Instance

# This will give manual run option
on: 
 workflow_dispatch:
   inputs:
     branch_name:
       description: 'Branch to create a duplicate'
       required: true

jobs:
  create_an_test_branch:
   runs-on: ubuntu-latest

   steps:
   # Step 1 - checkout repository
   - name: checkout repository
     uses: actions/checkout@v3

   # Step 2 - Get the current branch
   - name: get current branch
     id: get_branch
     run: |
       CURRENT_BRANCH="${{ github.event.inputs.branch_name }}"
       echo "Current is ${{CURRENT_BRANCH}}"
