name: Auto Create Branch Workflow

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to create a TEST branch from'
        required: true
        default: 'CH31421515'

jobs:
  create-an-test-branch:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Create and Push TEST Branch
    - name: Create TEST branch
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # Access the PAT from GitHub Secrets
      run: |
        BRANCH_NAME="${{ github.event.inputs.branch_name }}"  
        TEST_BRANCH_NAME="${BRANCH_NAME}_TEST"

        # Set git configuration for user details
        git config --global user.email "naren312suren@gmail.com"
        git config --global user.name "Narendar V"

        # Create a new branch
        git checkout -b "$TEST_BRANCH_NAME"
        git remote -v

        # Push the new branch to the repository using the PAT
        git push https://$PAT_TOKEN@github.com/${{ github.repository }} "$TEST_BRANCH_NAME"
